#!/usr/bin/env bash
# This script displays the content of the current directory in list format showing only part after first dash
for file in *
do
    if [[ "$file" != .* ]]
    then
        echo "$file" | cut -d'-' -f2-
    fi
done
