#!/usr/bin/env bash
# This script creates a PID file, displays messages indefinitely, and handles signals
pidfile="/var/run/myscript.pid"
echo $$ > "$pidfile"

cleanup() {
    rm -f "$pidfile"
    exit
}

trap "echo 'I hate the kill command'; cleanup" SIGTERM
trap "echo 'Y U no love me?!'" SIGINT
trap "cleanup" SIGQUIT

while true
do
    echo "To infinity and beyond"
    sleep 2
done
